controller_manager:
  ros__parameters:
    update_rate: 600  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    platform_velocity_controller:
      type: clearpath_mecanum_drive_controller/MecanumDriveController
    # puma_control: ???
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController
    right_joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    left_robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    right_robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    left_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    right_force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
      - lift_left_upper_joint
      - lift_right_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - left_robotiq_85_left_knuckle_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
      - right_robotiq_85_left_knuckle_joint
    interfaces:
      - position
      - velocity


platform_velocity_controller:
  ros__parameters:
    use_sim_time: False
    interface_name: 'velocity'
    command_joint_names: ['front_left_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint', 'front_right_wheel_joint']
    front_left_wheel_command_joint_name: 'front_left_wheel_joint'
    front_right_wheel_command_joint_name: 'front_right_wheel_joint'
    rear_right_wheel_command_joint_name: 'rear_right_wheel_joint'
    rear_left_wheel_command_joint_name: 'rear_left_wheel_joint'

    kinematics.base_frame_offset:
      x: 0.0
      y: 0.0
      theta: 0.0
    kinematics.wheels_radius: 0.0759
    kinematics.sum_of_robot_center_projection_on_X_Y_axis: 0.59
    wheel_separation_multiplier: 1.0
    wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    reference_timeout: 0.1
    use_stamped_vel: False

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

    cmd_vel_timeout: 0.5

    base_frame_id: 'base_link'
    odom_frame_id: 'odom'
    enable_odom_tf: False

    linear.x.has_velocity_limits: True
    linear.x.has_acceleration_limits: True
    linear.x.has_jerk_limits: False
    linear.x.max_velocity: 1.3
    linear.x.min_velocity: -1.3
    linear.x.max_acceleration: 1.0
    linear.x.min_acceleration: -1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0
    linear.y.has_velocity_limits: True
    linear.y.has_acceleration_limits: True
    linear.y.has_jerk_limits: False
    linear.y.max_velocity: 1.3
    linear.y.min_velocity: -1.3
    linear.y.max_acceleration: 1.0
    linear.y.min_acceleration: -1.0
    linear.y.max_jerk: 0.0
    linear.y.min_jerk: 0.0
    angular.z.has_velocity_limits: True
    angular.z.has_acceleration_limits: True
    angular.z.has_jerk_limits: False
    angular.z.max_velocity: 4.0
    angular.z.min_velocity: -4.0
    angular.z.max_acceleration: 2.0
    angular.z.min_acceleration: -2.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0


joint_trajectory_controller:
  ros__parameters:
    joints:
      - lift_left_upper_joint
      - lift_right_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - lift_left_upper_joint
      - lift_right_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false


left_joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      # the jtac can only be initialized on a chain that starts at the root node so must include the world actuator joints
      - lift_left_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
    base_frame: base_link
    sensor_frame: left_ft_frame
    ee_frame: left_ft_frame
    ft_sensor_name: left_tcp_fts_sensor
    ft_force_deadband: 2.0
    stop_accelerations: [1.0, 3.0, 3.0, 3.0, 5.0, 5.0, 5.0]

right_joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      # the jtac can only be initialized on a chain that starts at the root node so must include the world actuator joints
      - lift_right_upper_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    base_frame: base_link
    sensor_frame: right_ft_frame
    ee_frame: right_ft_frame
    ft_sensor_name: right_tcp_fts_sensor
    ft_force_deadband: 2.0
    stop_accelerations: [1.0, 3.0, 3.0, 3.0, 5.0, 5.0, 5.0]


servo_controller:
  ros__parameters:
    joints:
      - lift_left_upper_joint
      - lift_right_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - lift_left_upper_joint
      - lift_right_upper_joint
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false


left_robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: left_robotiq_85_left_knuckle_joint
    allow_stalling: true


right_robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: right_robotiq_85_left_knuckle_joint
    allow_stalling: true


left_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: left_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: left_ft_frame


right_force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: right_tcp_fts_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: right_ft_frame

puma_control:
  ros__parameters:
    canbus_dev: 'vcan0'
    joint_names: ['front_left_wheel_joint', 'front_right_wheel_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint']
    joint_can_ids: [5, 4, 2, 3]
    joint_directions: [-1, 1, -1, 1]
    gear_ratio: 34.97
    encoder_cpr: 1024
    gain:
      p: 0.1
      i: 0.01
      d: 0.0
