left_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005

right_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005

left_mobile_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005

right_mobile_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005

mobile_base:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005

manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "optimize_distance"
  optimization_timeout: 0.005