left_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

right_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

left_mobile_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

right_mobile_manipulator:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

mobile_base:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

arms_lift_only:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"

arms_only:
  kinematics_solver: pose_ik_plugin/PoseIKPlugin
  target_tolerance: 0.001
  solve_mode: "first_found"
