hardware:
  simulated: false

  # If the MoveIt Pro Agent should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: true

  # TODO: should we launch the robot state publisher or is this already done by the ros2_control drivers?
  # If the MoveIt Pro Agent should launch the robot state publisher.
  # This should be false if you are launching the robot state publisher as part of drivers.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # TODO: need to create this w/ 2 ur drivers to persist from our ur hardware AND figure out robot drivers to persist for the clearpath...battery details & estop stuff, otherwise the ros2 control tags in the description should launch the drivers.
  # NOTE: this is what will be run when we do moveit_pro --drivers-only which is all we want to run on the clearpath
  robot_driver_persist_launch_file:
    package: "dual_arm_mobile_hw"
    path: "launch/robot_drivers_to_persist.launch.py"

  robot_description:
    urdf:
      package: "dual_arm_mobile_hw"
      path: "description/dual_arm_mobile_hw.urdf"
    # TODO: need to verify srdf groups are ok for what we need
    srdf:
      package: "dual_arm_mobile_hw"
      path: "config/moveit/dual_arm_mobile_hw.srdf"
    urdf_params: []

moveit_params:
  joint_group_name: "manipulator"
  servo:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/servo.yaml"
  joint_limits:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/joint_limits.yaml"
  servo_joint_limits:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/hard_joint_limits.yaml"
  # TODO: may need to alter some things in here depending on the planning groups we end up with
  ompl_planning:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/pose_ik_distance.yaml"
  sensors_3d:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/sensors_3d.yaml"
  servo_kinematics:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/pose_ik_speed.yaml"
  pose_jog:
    package: "dual_arm_mobile_hw"
    path: "config/moveit/pose_jog.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "dual_arm_mobile_hw"
    path: "config/control/dual_arm_mobile.ros2_control.yaml"
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "left_robotiq_gripper_controller"
    - "right_robotiq_gripper_controller"
    - "left_force_torque_sensor_broadcaster"
    - "right_force_torque_sensor_broadcaster"
    - "joint_trajectory_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  controllers_inactive_at_startup:
    - "servo_controller"
    - "base_trajectory_controller"
    - "left_full_trajectory_admittance_controller"
    - "right_full_trajectory_admittance_controller"
    - "base_velocity_force_controller"
    - "left_velocity_force_controller"
    - "right_velocity_force_controller"
    - "left_joint_trajectory_controller"
    - "right_joint_trajectory_controller"
    - "right_full_trajectory_controller"

objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Pro Behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
      - "moveit_studio::behaviors::MTCCoreBehaviorsLoader"
      - "moveit_studio::behaviors::NavBehaviorsLoader"
      - "moveit_studio::behaviors::ServoBehaviorsLoader"
      - "moveit_studio::behaviors::VisionBehaviorsLoader"
      - "moveit_studio::behaviors::ConverterBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/core"
    motion_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/motion"
    perception_objectives:
      package_name: "moveit_pro_objectives"
      relative_path: "objectives/perception"
    sim_objectives:
      package_name: "dual_arm_mobile_hw"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "dual_arm_mobile_hw"
    relative_path: "waypoints/waypoints.yaml"
